gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#6c7086"
    searchingActiveBorderColor:
      - "#f9e2af"
      - bold
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#45475a"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#cba6f7"
    markedBaseCommitBgColor:
      - "#f9e2af"
    markedBaseCommitFgColor:
      - "#11111b"
    unstagedChangesColor:
      - "#f38ba8"
    stagedChangesColor:
      - "#a6e3a1"
    defaultFgColor:
      - "#cdd6f4"
    optionsTextColor:
      - "#89b4fa"
  authorColors:
    "*": "#b4befe"
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --syntax-theme=ansi
