gui:
  showIcons: false
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#6c7086"
    selectedLineBgColor:
      - "#313244"
    optionsTextColor:
      - "#89b4fa"
    defaultFgColor:
      - "#cdd6f4"
    entityStatColor:
      - "#f38ba8"
