## name: Cursor Dark
## blurb: Based on the Cursor dark theme (Nord-inspired palette)

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

foreground                      #d8dee9
background                      #191c22
selection_foreground            #eceff4
selection_background            #434c5e
url_color                       #88c0d0


#: kitty window border colors and terminal bell colors

active_border_color             #88c0d0
inactive_border_color           #4c566a
bell_border_color               #ebcb8b
visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color          system
macos_titlebar_color            system


#: Tab bar colors

active_tab_foreground           #1e2127
active_tab_background           #88c0d0
inactive_tab_foreground         #4c566a
inactive_tab_background         #191c22
tab_bar_background              #191c22
tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

mark1_foreground black
mark1_background #88c0d0
mark2_foreground black
mark3_foreground black
mark3_background #b48ead


#: The basic 16 colors

#: black
color0 #272c36
color8 #4c566a

#: red
color1 #bf616a
color9 #bf616a

#: green
color2 #a3be8c
color10 #a3be8c

#: yellow
color3 #ebcb8b
color11 #ebcb8b

#: blue
color4 #81a1c1
color12 #81a1c1

#: magenta
color5 #7d7c9b
color13 #b48ead

#: cyan
color6 #88c0d0
color14 #8fbcbb

#: white
color7  #e5e9f0
color15 #eceff4
